sonar.projectKey=LosQueSon_MIRALO-BACKEND
sonar.organization=losqueson
sonar.projectName=MIRALO-BACKEND
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts

# Excluir archivos sin cobertura de tests
sonar.exclusions=src/**/Repository.ts,src/**/*-handler.ts,src/**/*/chat.ts,src/**/*/room.ts,src/**/*/user.ts,src/**/watchSyncBus.ts,src/**/Routes.ts,src/config/**,src/plugins/**,src/miralo.ts,src/modules/realtime/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

