sonar.projectKey=LosQueSon_MIRALO-BACKEND
sonar.organization=losqueson
sonar.projectName=MIRALO-BACKEND
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8

